### ISSUE TITLE
Fresh install not working

### ISSUE THREAD

**Issue by Soviet-Steve** [mskian/cricket-cli#73]
After a fresh install this issue comes up instead of running the command

file:///usr/local/lib/node_modules/cricket-cli/node_modules/boxen/index.js:17
        if (stdout?.columns) {
                   ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)

**Comment by mskian** [comment]
your node version?

i am tested with node 16 and 18 no issues
